//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDI_Utilities.Properties
{


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        internal string conversionDelimiter;
        internal int conversionDescriptionCol;
        internal bool conversionDisjoint;
        internal bool conversionHoldSegValue;
        internal int conversionIdocFieldCol;
        internal int conversionIdocSegmentCol;
        internal bool conversionIntenseSearch;
        internal int conversionSkipFirstX;
        internal int conversionX12Col;
        internal bool explorerSmartMode;
        internal bool fallbackSearchEnabled;

        public static Settings Default
        {
            get
            {
                return defaultInstance;
            }
        }
    }
}
